spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai
    username: postgres
    password: ${HETZNER_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

#OTHER
playwright:
  headless: true

scheduler:
  heatmap:
    cron: "0 0 12 * * *"
    save-to-target: false
  process-currencies: "0 0 8,20 * * *"
  low-price-alert: "0 15 21 ? * MON-SAT"
  owned-stock-alert: "0 15 8 ? * WED,SAT"
  trend-checker: "0 0 8 ? * SAT"
  analyst-insights: "0 0 1 ? * SAT"