--
-- PostgreSQL database dump
--

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alert_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.alert_config (
    percent_change_threshold integer CONSTRAINT low_price_alert_config_percent_change_threshold_not_null NOT NULL,
    created_date timestamp(6) without time zone,
    id bigint CONSTRAINT low_price_alert_config_id_not_null NOT NULL,
    modified_date timestamp(6) without time zone,
    ticker character varying(255),
    alert_type character varying(255)
);


--
-- Name: currency_rate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.currency_rate (
    rate numeric(38,2),
    created_date timestamp(6) without time zone,
    id bigint NOT NULL,
    ratio_date timestamp(6) without time zone,
    symbol character varying(255)
);


--
-- Name: currency_rate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.currency_rate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_rate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: heatmap; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.heatmap (
    ratio double precision NOT NULL,
    created_date timestamp(6) without time zone,
    id bigint NOT NULL,
    base64 text,
    model_version character varying(255),
    source character varying(255)
);


--
-- Name: heatmap_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.heatmap ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.heatmap_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: low_price_alert_config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.alert_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.low_price_alert_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: owned_stock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.owned_stock (
    "position" integer NOT NULL,
    purchase_price numeric(38,2),
    bought_date timestamp(6) without time zone,
    created_date timestamp(6) without time zone,
    id bigint NOT NULL,
    modified_date timestamp(6) without time zone,
    currency character varying(255),
    name character varying(255),
    ticker character varying(255)
);


--
-- Name: owned_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.owned_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.owned_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currency_rate currency_rate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency_rate
    ADD CONSTRAINT currency_rate_pkey PRIMARY KEY (id);


--
-- Name: heatmap heatmap_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.heatmap
    ADD CONSTRAINT heatmap_pkey PRIMARY KEY (id);


--
-- Name: alert_config low_price_alert_config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alert_config
    ADD CONSTRAINT low_price_alert_config_pkey PRIMARY KEY (id);


--
-- Name: owned_stock owned_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.owned_stock
    ADD CONSTRAINT owned_stock_pkey PRIMARY KEY (id);


--
-- Name: owned_stock owned_stock_ticker_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.owned_stock
    ADD CONSTRAINT owned_stock_ticker_key UNIQUE (ticker);


--
-- Name: alert_config ukqe80wdgsp7fuqawthuemi5hlt; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alert_config
    ADD CONSTRAINT ukqe80wdgsp7fuqawthuemi5hlt UNIQUE (ticker, alert_type);


--
-- PostgreSQL database dump complete
--

